### ISSUE TITLE
Not Compatible with Multiprocess

### ISSUE THREAD

**Issue by mrnfrancesco** [johan-adriaans/hackbar#30]
Firefox Multiprocess is now available to the public, however add-ons must support it for it to function. This extension is one of the extensions I have which is blocking support.

**Comment by plaguna** [comment]
Hi @mrnfrancesco,

Firefox is planning to remove any support for XUL extensions (https://developer.mozilla.org/en-US/Add-ons/Overlay_Extensions) and move to an only WebExtensions world.

> Starting from Firefox 53, no new legacy add-ons will be accepted on addons.mozilla.org (AMO) for desktop Firefox and Firefox for Android.
> 
> Starting from Firefox 57, WebExtensions will be the only supported extension type. Desktop Firefox and Firefox for Android will not load other extension types. 

This means that before the end of the year this extension will probably stop working on latest Firefox versions.

**Comment by mrnfrancesco** [comment]
Yep, I read about the xul support deprecation.
No one would fork this project to follow the new coding standard and fix the posted issues?

**Comment by plaguna** [comment]
Without XUL there's no way to modify Firefox UI, which is key for the "hackbar look&feel". The only option is to create a WebDeveloper WebExtension and try to replicate the interface but with current webdev toolkit you can pretty much achieve these functionalities already.
